spring.application.name=designdrop-backend

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/designdrop_db
spring.datasource.username=root
spring.datasource.password=Udara@200319
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Server Port
server.port=8080
